### ISSUE TITLE
Commands aren't working

### ISSUE THREAD

**Issue by AdminRAT** [Adikso/BashBot#1]
When trying to type a command, it would show the output of me doing the cmd in terminal, but nothing would happen in Discord. I tried changing permissions.json and settings,json, but no luck.

**Comment by Adikso** [comment]
Are you typing command with "$" or ".bash" prefix? Like "$.help". Now I see that I didn't mentioned prefixes in readme.

**Comment by AdminRAT** [comment]
Before I was trying "$help" and ".bashhelp", nut now that you mentioned "$.help", it works...
So yea something in the readme was missing then (since I first noticed ".help")
