### ISSUE TITLE
Having an issue

### ISSUE THREAD

**Issue by j-dogcoder** [Adikso/BashBot#27]
<img width="360" alt="Screen Shot 2020-12-22 at 5 24 58 PM" src="https://user-images.githubusercontent.com/65788728/102938623-a9c6a980-447a-11eb-9550-bd7a53ebb71a.png">

**Comment by Adikso** [comment]
Have you read "Installing" section in readme?

**Comment by j-dogcoder** [comment]
@Adikso Yes. Still get the same thing

**Comment by Adikso** [comment]
You are probably using pip for different version of python. Try using `python -m pip install -r requirements.txt` it should make it use correct pip.

**Comment by j-dogcoder** [comment]
Now it gives
<img width="781" alt="Screen Shot 2020-12-23 at 10 19 45 AM" src="https://user-images.githubusercontent.com/65788728/103011724-63b82700-4508-11eb-801c-cdb485230a4c.png">

**Comment by j-dogcoder** [comment]
@Adikso ?

**Comment by Adikso** [comment]
You are using Python 2 which is not supported by BashBot. You can try use "python3" instead of "python" command to explicitly use python 3.

**Comment by j-dogcoder** [comment]
<img width="333" alt="Screen Shot 2020-12-23 at 3 40 03 PM" src="https://user-images.githubusercontent.com/65788728/103035366-2918b380-4535-11eb-93c7-af05573dbeaf.png">

**Comment by j-dogcoder** [comment]
@Adikso It gives me this now.

**Comment by j-dogcoder** [comment]
@Adikso  I used python 3 and even installed both pip3 and python3

**Comment by Adikso** [comment]
> Now it gives
> <img alt="Screen Shot 2020-12-23 at 10 19 45 AM" width="781" src="https://user-images.githubusercontent.com/65788728/103011724-63b82700-4508-11eb-801c-cdb485230a4c.png">



> Now it gives
> <img alt="Screen Shot 2020-12-23 at 10 19 45 AM" width="781" src="https://user-images.githubusercontent.com/65788728/103011724-63b82700-4508-11eb-801c-cdb485230a4c.png">

There is messenge on this screen shot saying that you're using python 2

**Comment by j-dogcoder** [comment]
Sorry wrong screenshot.

**Comment by j-dogcoder** [comment]
<img width="331" alt="Screen Shot 2020-12-23 at 4 14 39 PM" src="https://user-images.githubusercontent.com/65788728/103037499-f6bd8500-4539-11eb-881e-b80db9caa3d3.png">

**Comment by Adikso** [comment]
You still didn't installed dependencies. Show me a screenshot where you are installing dependencies.

**Comment by j-dogcoder** [comment]
![Uploading Screen Shot 2020-12-23 at 4.18.21 PM.png…]()

**Comment by j-dogcoder** [comment]
<img width="1439" alt="Screen Shot 2020-12-23 at 4 19 06 PM" src="https://user-images.githubusercontent.com/65788728/103037757-967b1300-453a-11eb-9505-14deb19bd31b.png">

**Comment by Adikso** [comment]
You are installing dependencies for python3 and running bashbot with python2.
Run bashbot with "python3" command

**Comment by j-dogcoder** [comment]
<img width="591" alt="Screen Shot 2020-12-23 at 4 21 16 PM" src="https://user-images.githubusercontent.com/65788728/103037870-e35ee980-453a-11eb-83a2-c9167543eacc.png">

**Comment by Adikso** [comment]
Now you have working bot. Do what message says and your are good to go

**Comment by j-dogcoder** [comment]
thanks!
