### ISSUE TITLE
Bashbot module not coming

### ISSUE THREAD

**Issue by Vichu2005g** [Adikso/BashBot#28]
I installed all the required stuff but i can't find bashbot.py module. What to do?

**Comment by Adikso** [comment]
Could you share logs with error?

**Comment by Vichu2005g** [comment]
sorry for the lateness. I just installed all the required module by putting pip install <the module>. I just install all the modules and hosted i repl.it and it works! Thanks for the bot and sorry for confusion and thanks for the bot ;). I am closing this issue
