### ISSUE TITLE
Does this work on Windows?

### ISSUE THREAD

**Issue by CE1CECL** [Adikso/BashBot#37]
Hi there!
Whenever I try this on Windows 10 2004, I keep getting in discord "Waiting for tty.." and it never moves. Nothing shows up in logs.
Please Help!

**Comment by Adikso** [comment]
No, it is not designed to work on Windows at all. Multiple components of BashBot would fail even after "Waiting for tty.." because it requires Linux features missing on Windows.
You have to use Linux distribution in order to run BashBot.

**Comment by Adikso** [comment]
You could try running docker image on Windows. It should work.
