### ISSUE TITLE
Please help new problem

### ISSUE THREAD

**Issue by MC-HackerTech** [Adikso/BashBot#41]
I get a error like this
    from discord import LoginFailure
ModuleNotFoundError: No module named 'discord'
 I also tried install this discord and also install discord.js, discord.py 
but it does not work

**Comment by MC-HackerTech** [comment]
How do I fix this? 
do I have to install discord in my OS?
I have Windows 10 64-bit

**Comment by MC-HackerTech** [comment]
I tried to uninstall and reinstall the discord using python pip

**Comment by Adikso** [comment]
"pip install -r requirements.txt" from readme should be enough but BashBot does not support Windows. Only linux distros are supported.

**Comment by 4RCAN3** [comment]
Did you try `py -3 -m pip install -U discord.py`?

**Comment by MC-HackerTech** [comment]
Hmm not yet

**Comment by MC-HackerTech** [comment]
I did pip install -r requirements.txt

**Comment by MC-HackerTech** [comment]
Ok that got fixed coz I ran it on my android using temux instead of running it in my kali linux or windows 10

**Comment by MC-HackerTech** [comment]
But Now I got another error
```
[2021-03-06 19:16:32] INFO:discord.client: logging in using static token
[2021-03-06 19:16:33] INFO:discord.client: Cleaning up tasks.
[2021-03-06 19:16:33] INFO:discord.client: Closing the event loop.
[2021-03-06 19:16:33] ERROR:Launcher: Improper token has been passed.
```
now how do I fix this?
