### ISSUE TITLE
ARM docker image?

### ISSUE THREAD

**Issue by legendofmiracles** [Adikso/BashBot#43]
I'd love to run this on my pi, in a docker container.
Thoughts?

**Comment by Adikso** [comment]
Have you tried building docker image yourself? I think that it should work because base image supports arm64
You can try running:
```
docker build -t bashbot-test .
mv config.toml.example config.toml
docker run -v $(pwd)/config.toml:/BashBot/config.toml bashbot-test
```

**Comment by legendofmiracles** [comment]
I did try running that, but it didn't work.
Then i saw there was a *working* container on docker hub and tried that.
Unfortunately i don't anymore have the output, only a screenshot: https://media.discordapp.net/attachments/805876093101932545/818059346797395978/unknown.png?width=755&height=684.

If you need the output, let me know and i'll build it again (building takes a while).

**Comment by Adikso** [comment]
Can you show full output of building?

**Comment by legendofmiracles** [comment]
Here: http://0x0.st/-ZRJ.txt

**Comment by Adikso** [comment]
Does installing BashBot without using docker works?
