### ISSUE TITLE
Terminal not starting

### ISSUE THREAD

**Issue by hex-developer** [Adikso/BashBot#50]
I am trying to open a terminal and the bot responds with "waiting for tty" and a terminal never opens.

**Comment by Potaot** [comment]
After some debugging I found that the terminal did start, so there is no problem. I was just expecting the bot to send back the text in the terminal

**Comment by Potaot** [comment]
I just noticed that in the screen shot you provide, there is a terminal. It isn't showing up for me

**Comment by Adikso** [comment]
I'm not really maintaining it now, but are you running it on linux?

**Comment by Potaot** [comment]
I am running it on an Ubuntu 22.04 computer with Python 3.10.4

**Comment by hex-developer** [comment]
I'm closing this issue now as I haven't found any solution to the problem and I lost interest in this project. I will probably check out the docker container though.
