### ISSUE TITLE
Suggestion: Make persistant controls or bulk controls add a thing

### ISSUE THREAD

**Issue by CNSabata** [Adikso/BashBot#7]
Hi, I tend to use controls quite alot, I have even set up a particular set of commands for when I want to use them so I just have to copy paste, and as you can see, it's quite long...

### Arrows : 
> That's already 4 characters.

- $.controls add :arrow_up: [UP]
- $.controls add :arrow_down: [DOWN]
- $.controls add :arrow_left: [LEFT]
- $.controls add :arrow_right: [RIGHT]

### Important Keys : 
> 3 more.

- $.controls add :x: [ESC]
- $.controls add :cl: [<]
- $.controls add :next_track_button: [TAB]

### Function Keys : 
> And append another 12...

- $.controls add :one: [F1]
- $.controls add :two: [F2]
- $.controls add :three: [F3]
- $.controls add :four: [F4]
- $.controls add :five: [F5]
- $.controls add :six: [F6]
- $.controls add :seven: [F7]
- $.controls add :eight: [F8]
- $.controls add :nine: [F9]
- $.controls add :keycap_ten: [F10]
- $.controls add :a: [F11]
- $.controls add :b: [F12]

### The rest of the escaped characters : 
> Add another final 7.

- $.controls add :bell: \a
- $.controls add :back: \b
- $.controls add :arrow_right_hook: \f
- $.controls add :leftwards_arrow_with_hook: \n
- $.controls add :arrow_heading_down: \r
- $.controls add :left_right_arrow: \t
- $.controls add :arrow_up_down: \v

So in total, that makes us _4 + 3 + 12 + 7 = **26 keys**_ to set, so with character count for all commands, removing whitespaces in between sections that makes us a whopping **765 characters** to type. 
Honestly that's almost half of discord's allowed per message character limit. That's way too much. Please either make a configuration file; a save command; a startup preset or bulk insertion. That's way too much.

**Comment by Adikso** [comment]
Sorry for not responding. I will be rewriting bashbot in few days and I will probably add "macros" ;)

**Comment by Adikso** [comment]
There is updated version of the bot on master branch now. It has "$.macro example" executing commands from file
